# server:
#   port: 8076 # 포트를 동적으로 할당 받기 위해 0으로 변경


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: P@ssw0rd
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: ecommerce-customer

http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
management:
    endpoints:
        web:
            exposure:
                include: "*"

#eureka
eureka:
  client:
    register-with-eureka: true # 자신의 서비스 정보 eureka 등록 여부
    fetch-registry: true # eureka의 서비스 목록 정보를 local에 caching 하는 설정





