server:
  port: 8076


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: P@ssw0rd
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: ecommerce-customer

http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
management:
    endpoints:
        web:
            exposure:
                include: "*"





