server:
  port: 8076 # 포트를 동적으로 할당 받기 위해 0으로 변경


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: P@ssw0rd
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: ecommerce-customer

http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
management:
    endpoints:
        web:
            exposure:
                include: "*"
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10 # circuit breaker가 닫혀있을 때 사용할 sliding window의 사이즈
        minimum-number-of-calls: 5 # circuit breaker가 error rate 나 slow call rate를 계산하기 위한 최소한의 call 수
        permittedNumberOfCallsInHalfOpenState: 3 # circuit breaker가 half open 상태일 때 허용된 요청을 얼마나 받을 지
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s # open에서 half-open으로 넘어가기 전 얼마나 open 상태를 유지할 것인지

        failureRateThreshold: 50 # 실패율 threshold. 이 실패율을 넘기면 circuit breaker open
        eventConsumerBufferSize: 10
        ignore-exceptions:
          - java.util.NoSuchElementException
    instances:
      example:
        base-config: default

#eureka
eureka:
  client:
    register-with-eureka: true # 자신의 서비스 정보 eureka 등록 여부
    fetch-registry: true # eureka의 서비스 목록 정보를 local에 caching 하는 설정





