server:
  port: 8070


spring:
  application:
    name: ecommerce-gateway
  cloud:
    gateway:
      routes:
      - id: ecommerce-orders
        uri: lb://ECOMMERCE-ORDERS
        predicates:
        - Path=/api/orders/**
        filters:
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/fallback


      - id: ecommerce-customer
        uri: lb://ECOMMERCE-CUSTOMER
        predicates:
        - Path=/api/customer/**
        filters:
        - AddResponseHeader=X-Response-Red, Blue

      - id: fallback
        uri: http://localhost:9000
        predicates:
        - Path=/fallback
      
      
#eureka
eureka:
  client:
    register-with-eureka: true # 자신의 서비스 정보 eureka 등록 여부
    fetch-registry: true # eureka의 서비스 목록 정보를 local에 caching 하는 설정
management:
  endpoints:
    web:
      exposure:
        include:
        - "gateway"
  endpoint:
    gateway:
      enabled: true

          