
server:
  port: 8074


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: P@ssw0rd
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: ecommerce-order
  main:
    allow-circular-references: true

http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
management:
    endpoints:
        web:
            exposure:
                include: "*"

customer:
  api:
    url: http://localhost:8076

resilience4j.circuitbreaker:
  configs:
    default:
      waitDurationInOpenState: 5000

resilience4j:
  bulkhead:
    instances:
      customer:
        max-concurrent-calls: 1
        max-wait-duration: 10ms

#eureka
eureka:
  client:
    register-with-eureka: true # 자신의 서비스 정보 eureka 등록 여부
    fetch-registry: true # eureka의 서비스 목록 정보를 local에 caching 하는 설정

        





