server:
  port: 8761

spring:
  application:
    name: ecommerce-eureka

#eureka
eureka:
  client:
    register-with-eureka: false # 자신의 서비스 정보 eureka 등록 여부
    fetch-registry: false # eureka의 서비스 목록 정보를 local에 caching 하는 설정