server:
  port: 9000 # 포트를 동적으로 할당 받기 위해 0으로 변경
#eureka
eureka:
  client:
    register-with-eureka: true # 자신의 서비스 정보 eureka 등록 여부
    fetch-registry: true # eureka의 서비스 목록 정보를 local에 caching 하는 설정
spring:
  application:
    name: ecommerce-fallback